<?php return array (
  'db_host' => '127.0.0.1',
  'db_port' => 3307,
  'db_name' => 'quick',
  'db_user' => 'root',
  'db_pass' => 'pospwnet',
  'settings_pin' => '1234',
  'computer_id' => 5,
  'product_level_id' => 2,
  'queue_refresh_ms' => 5000,
  'ready_limit' => 30,
  'preparing_limit' => 30,
  'ready_display_minutes' => 30,
  'grid_columns' => 5,
  'bg_image' => 'images/bg-matcha.svg',
  'color_header_bg' => '#2d5a1b',
  'color_header_text' => '#f0f5eb',
  'color_queue_text' => '#1e3d10',
  'color_app_bg' => '#f0f5eb',
  'sound_enabled' => 1,
  'sound_volume' => 70,
  'show_computer_name' => 0,
);
